### ISSUE TITLE
Repo should enforce the node version

### ISSUE THREAD

**Issue by poolpitako** [pimlicolabs/tutorial-template#16]
I was running the template with node 16 and getting the following error:

```
% npm start

> pimlico-tutorial-template@1.0.0 start
> tsx index.ts

HttpRequestError: HTTP request failed.

URL: https://rpc.ankr.com/eth_sepolia
Request body: {"method":"eth_chainId"}

Details: Request is not defined
Version: viem@2.9.23
    at Object.request (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/rpc/http.ts:137:15)
    at fn (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/clients/transports/http.ts:124:19)
    at request (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/clients/transports/http.ts:129:39)
    at withRetry.delay.count.count (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/buildRequest.ts:104:18)
    at attemptRetry (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/promise/withRetry.ts:44:22)
```

Updating to node 18 fixed the issue.

**Comment by Dropkick13** [comment]
Great

**Comment by tamarastafferd** [comment]
> I was running the template with node 16 and getting the following error:
> 
> ```
> % npm start
> 
> > pimlico-tutorial-template@1.0.0 start
> > tsx index.ts
> 
> HttpRequestError: HTTP request failed.
> 
> URL: https://rpc.ankr.com/eth_sepolia
> Request body: {"method":"eth_chainId"}
> 
> Details: Request is not defined
> Version: viem@2.9.23
>     at Object.request (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/rpc/http.ts:137:15)
>     at fn (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/clients/transports/http.ts:124:19)
>     at request (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/clients/transports/http.ts:129:39)
>     at withRetry.delay.count.count (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/buildRequest.ts:104:18)
>     at attemptRetry (file:///Users/user/dev/pimlico-tutorial-1/node_modules/viem/utils/promise/withRetry.ts:44:22)
> ```
> 
> Updating to node 18 fixed the issue.
